### ISSUE TITLE
你有没有发现electron不能透明，启动参数设置透明，但嵌入桌面会显示为黑色背景!

### ISSUE THREAD

**Issue by goodhelp** [leejoker/fliplo_desktop#1]
你这个代码对html5要求不高，应该使用aardio中的kit，有layeredWindow透明层窗口，使用你的代码在win7中测试，桌面都成全黑了！

我也在找electron背景不能透明的问题，貌似aardio作者透明不推荐使用electron，在electron的启动参数中加入 transparent: true，背景并不透明，而是变成黑色了!

**Comment by leejoker** [comment]
我一直用的win10，所以也没有发现这个问题:smile:
至于您说的kit，我也是刚接触aardio，我去学习一下，看看能否做出修改
感谢您的回复~

**Comment by kongKhuai** [comment]
请问你们的win7系统的设备不能透明，electron窗口显示黑色背景的问题处理好了吗，我尝试过关闭gpu加速，开启area主题，窗口启动后动态设置透明度、背景色、大小等强制重绘，等都没生效，我自己的win7虚拟机可以通过更新显卡驱动使透明窗口正常，但是客户的win7不能继续更新显卡驱动也不能重新进行系统评估，期待你们的回复
